# 凡例 ------------------------------------------------------------------------
# application: 起動するアプリケーションのパス
# arguments: アプリケーションに渡す引数のリスト (NOTE要参照)
# purpose_choices: 使用目的の選択肢のリスト
# destination_names: 接続先サーバー名のリスト
# output_file_path: 出力先Excelファイルのパス
# sheet_name: 出力先Excelシート名
# base_row: Excelのベース行 (見出し行の次の行番号)
# NOTE -----------------------------------------------------------------------
# - パス指定時などにシングルクオート(')で囲むとエスケープが不要になるため便利です。
# - argumentsリストの0番目の値は何でもよく、実際に渡す引数は1番目以降に入れます。
# ----------------------------------------------------------------------------
# application = 'C:\WINDOWS\system32\mstsc.exe'
application = "/bin/echo"  # DEBUG
# arguments = ["mstsc", '%UserProfile%\Desktop\example.rdp']
arguments = ["echo", "RDB starting dummy."]  # DEBUG
purpose_choices = ["目的A", "目的B", "目的C"]
destination_names = ["Server A", "Server B", "Server C", "Server D"]
output_file_path = '../output/automation_sample.xlsx'  # DEBUG
sheet_name = "シート1"
base_row = 4
